In [1]:
import numpy as np
import pandas as pd
import glob
import os
import regex as re
import matplotlib.pyplot as plt
import csv

In [2]:
with open("../../data_files/data/TRAJETORIAS_DATASET_Epidemiological_dimension_indicators.csv", encoding="utf-8") as f:
    lines = f.readlines()

clean_lines = [line.replace('"', '') for line in lines]

trajetorias_epidem_df = pd.DataFrame(
    [line.strip().split(",") for line in clean_lines]
)

trajetorias_epidem_df.columns = trajetorias_epidem_df.iloc[0]
trajetorias_epidem_df = trajetorias_epidem_df[1:].reset_index(drop=True)

trajetorias_epidem_df.columns = trajetorias_epidem_df.columns.str.replace('\ufeff', '')

trajetorias_epidem_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,RO,Rondônia,Alta Floresta D'Oeste,1100015,2004-2008,rural,chagas,0,0
1,RO,Rondônia,Alto Alegre dos Parecis,1100379,2004-2008,rural,chagas,0,0
2,RO,Rondônia,Alto Paraíso,1100403,2004-2008,rural,chagas,0,0
3,RO,Rondônia,Alvorada D'Oeste,1100346,2004-2008,rural,chagas,0,0
4,RO,Rondônia,Ariquemes,1100023,2004-2008,rural,chagas,1,1.5033963749593
...,...,...,...,...,...,...,...,...,...
32419,MT,Mato Grosso,Vale de São Domingos,5108352,2015-2019,total,Vivax+Falciparum,0,0
32420,MT,Mato Grosso,Várzea Grande,5108402,2015-2019,total,Vivax+Falciparum,0,0
32421,MT,Mato Grosso,Vera,5108501,2015-2019,total,Vivax+Falciparum,0,0
32422,MT,Mato Grosso,Vila Bela da Santíssima Trindade,5105507,2015-2019,total,Vivax+Falciparum,0,0
32423,MT,Mato Grosso,Vila Rica,5108600,2015-2019,total,Vivax+Falciparum,0,0

In [3]:
with open("../../data_files/data/TRAJETORIAS_DATASET_Population_indicators.csv", encoding="utf-8") as f:
    lines = f.readlines()

clean_lines = [line.replace('"', '') for line in lines]

trajetorias_pop_df = pd.DataFrame(
    [line.strip().split(",") for line in clean_lines]
)

trajetorias_pop_df.columns = trajetorias_pop_df.iloc[0]
trajetorias_pop_df = trajetorias_pop_df[1:].reset_index(drop=True)

trajetorias_pop_df.columns = trajetorias_pop_df.columns.str.replace('\ufeff', '')

trajetorias_pop_df

,state_abbrev,state,municipality,geocode,urb2000,rur2000,tot2000,prop_urb2000,prop_rur2000,urb2010,rur2010,tot2010,prop_urb2010,prop_rur2010,pop_estimated2006,pop_estimated2017,urb2006e,rur2006e,urb2017e,rur2017e
0,RO,Rondônia,Alta Floresta D'Oeste,1100015,12341,14192,26533,0.465118908529002,0.534881091470998,13970,10422,24392,0.572728763529026,0.427271236470974,29005,25437,16611.9977861594,12393.0022138406,14568.5015578878,10868.4984421122
1,RO,Rondônia,Alto Alegre dos Parecis,1100379,2449,10259,12708,0.192713251495121,0.807286748504879,3657,9159,12816,0.285346441947566,0.714653558052434,15454,14045,4409.74391385768,11044.2560861423,4007.69077715356,10037.3092228464
2,RO,Rondônia,Alto Paraíso,1100403,4036,9082,13118,0.30766885195914,0.69233114804086,8202,8933,17135,0.478669390137146,0.521330609862854,16510,20916,7902.83163116428,8607.16836883572,10011.8489641086,10904.1510358914
3,RO,Rondônia,Alvorada D'Oeste,1100346,8546,11286,19832,0.430919725695845,0.569080274304155,8824,8029,16853,0.523586305108883,0.476413694891117,19542,16747,10231.9235744378,9310.07642556221,8768.49985165846,7978.50014834154
4,RO,Rondônia,Ariquemes,1100023,55118,19385,74503,0.739809135202609,0.260190864797391,76525,13828,90353,0.846955828804799,0.153044171195201,86924,107345,73620.7884630283,13303.2115369717,90916.4734430511,16428.5265569489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,MT,Mato Grosso,Vale de São Domingos,5108352,NA,NA,NA,NA,NA,713,2339,3052,0.233617300131062,0.766382699868938,3337,3041,779.580930537353,2557.41906946265,710.430209698558,2330.56979030144
768,MT,Mato Grosso,Várzea Grande,5108402,211303,3995,215298,0.981444323681595,0.0185556763184052,248704,3892,252596,0.984591996706203,0.0154080032937972,254736,274013,250811.026872951,3924.97312704872,269791.006793457,4221.99320654327
769,MT,Mato Grosso,Vera,5108501,8294,761,9055,0.915958034235229,0.0840419657647708,7349,2886,10235,0.718026380068393,0.281973619931607,11499,10901,8256.58534440645,3242.41465559355,7827.20556912555,3073.79443087445
770,MT,Mato Grosso,Vila Bela da Santíssima Trindade,5105507,2787,9878,12665,0.22005527043032,0.77994472956968,5166,9327,14493,0.356447940385013,0.643552059614987,14862,15534,5297.52929000207,9564.47070999793,5537.0623059408,9996.9376940592
771,MT,Mato Grosso,Vila Rica,5108600,10030,5553,15583,0.643650131553616,0.356349868446384,13962,7420,21382,0.652979141333832,0.347020858666168,20108,24835,13130.1045739407,6977.8954260593,16216.7369750257,8618.26302497428

In [4]:
manaus_epidem_df = trajetorias_epidem_df[trajetorias_epidem_df['municipality']=='Manaus']
manaus_epidem_df = manaus_epidem_df.reset_index(drop=True)
manaus_epidem_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,AM,Amazonas,Manaus,1302603,2004-2008,rural,chagas,1,2.3370470771129
1,AM,Amazonas,Manaus,1302603,2015-2019,rural,chagas,1,2.3370470771129
2,AM,Amazonas,Manaus,1302603,2004-2008,urban,chagas,4,0.0476200059128792
3,AM,Amazonas,Manaus,1302603,2015-2019,urban,chagas,10,0.119050014782198
4,AM,Amazonas,Manaus,1302603,2004-2008,total,chagas,5,0.0592233216702872
5,AM,Amazonas,Manaus,1302603,2015-2019,total,chagas,11,0.103273584870232
6,AM,Amazonas,Manaus,1302603,2004-2008,rural,CL,697,1628.92181274769
7,AM,Amazonas,Manaus,1302603,2015-2019,rural,CL,912,2131.38693432696
8,AM,Amazonas,Manaus,1302603,2004-2008,urban,CL,3005,35.7745294420505
9,AM,Amazonas,Manaus,1302603,2015-2019,urban,CL,1389,16.5360470532473
10,AM,Amazonas,Manaus,1302603,2004-2008,total,CL,3702,43.8489473646806
11,AM,Amazonas,Manaus,1302603,2015-2019,total,CL,2301,21.6029562533095
12,AM,Amazonas,Manaus,1302603,2004-2008,rural,VL,0,0
13,AM,Amazonas,Manaus,1302603,2015-2019,rural,VL,0,0
14,AM,Amazonas,Manaus,1302603,2004-2008,urban,VL,5,0.0595250073910989
15,AM,Amazonas,Manaus,1302603,2015-2019,urban,VL,2,0.0238100029564396
16,AM,Amazonas,Manaus,1302603,2004-2008,total,VL,5,0.0592233216702872
17,AM,Amazonas,Manaus,1302603,2015-2019,total,VL,2,0.0187770154309513
18,AM,Amazonas,Manaus,1302603,2004-2008,rural,Dengue,0,0
19,AM,Amazonas,Manaus,1302603,2015-2019,rural,Dengue,0,0
20,AM,Amazonas,Manaus,1302603,2004-2008,urban,Dengue,0,0
21,AM,Amazonas,Manaus,1302603,2015-2019,urban,Dengue,0,0
22,AM,Amazonas,Manaus,1302603,2004-2008,total,Dengue,10083,119.429750480301
23,AM,Amazonas,Manaus,1302603,2015-2019,total,Dengue,11155,104.728803566131
24,AM,Amazonas,Manaus,1302603,2004-2008,rural,Falciparum,22273,52053.0495485355
25,AM,Amazonas,Manaus,1302603,2015-2019,rural,Falciparum,78,182.289672014806
26,AM,Amazonas,Manaus,1302603,2004-2008,urban,Falciparum,44105,525.070090196884
27,AM,Amazonas,Manaus,1302603,2015-2019,urban,Falciparum,398,4.73819058833148
28,AM,Amazonas,Manaus,1302603,2004-2008,total,Falciparum,66378,786.225129166065
29,AM,Amazonas,Manaus,1302603,2015-2019,total,Falciparum,476,4.46892967256641
30,AM,Amazonas,Manaus,1302603,2004-2008,rural,Vivax,78745,184030.772087255
31,AM,Amazonas,Manaus,1302603,2015-2019,rural,Vivax,25859,60433.7003670624
32,AM,Amazonas,Manaus,1302603,2004-2008,urban,Vivax,183519,2184.79396628142
33,AM,Amazonas,Manaus,1302603,2015-2019,urban,Vivax,36387,433.187288787983
34,AM,Amazonas,Manaus,1302603,2004-2008,total,Vivax,262264,3106.42904690724
35,AM,Amazonas,Manaus,1302603,2015-2019,total,Vivax,62246,584.397051257497
36,AM,Amazonas,Manaus,1302603,2004-2008,rural,Vivax+Falciparum,433,1011.94138438988
37,AM,Amazonas,Manaus,1302603,2015-2019,rural,Vivax+Falciparum,8,18.6963766169032
38,AM,Amazonas,Manaus,1302603,2004-2008,urban,Vivax+Falciparum,1227,14.6074368137757
39,AM,Amazonas,Manaus,1302603,2015-2019,urban,Vivax+Falciparum,32,0.380960047303033
40,AM,Amazonas,Manaus,1302603,2004-2008,total,Vivax+Falciparum,1660,19.6621427945353
41,AM,Amazonas,Manaus,1302603,2015-2019,total,Vivax+Falciparum,40,0.375540308619026

In [5]:
manaus_vivax_df = manaus_epidem_df[manaus_epidem_df['disease']=='Vivax']
manaus_vivax_df = manaus_vivax_df.reset_index(drop=True)
manaus_vivax_df = manaus_vivax_df.drop(columns=['state_abbrev', 'state', 'municipality', 'geocode', 'disease'])

cols = ['cases', 'inc']

manaus_vivax_df[cols] = manaus_vivax_df[cols].apply(pd.to_numeric, errors='coerce')
manaus_vivax_df

0     period   zone   cases            inc
0  2004-2008  rural   78745  184030.772087
1  2015-2019  rural   25859   60433.700367
2  2004-2008  urban  183519    2184.793966
3  2015-2019  urban   36387     433.187289
4  2004-2008  total  262264    3106.429047
5  2015-2019  total   62246     584.397051

In [6]:
manaus_pop_df = trajetorias_pop_df[trajetorias_pop_df['municipality']=='Manaus']
manaus_pop_df = manaus_pop_df.reset_index(drop=True)
manaus_pop_df

,state_abbrev,state,municipality,geocode,urb2000,rur2000,tot2000,prop_urb2000,prop_rur2000,urb2010,rur2010,tot2010,prop_urb2010,prop_rur2010,pop_estimated2006,pop_estimated2017,urb2006e,rur2006e,urb2017e,rur2017e
0,AM,Amazonas,Manaus,1302603,1396768,9067,1405835,0.993550452222345,0.00644954777765527,1792881,9133,1802014,0.994931781884048,0.00506821811595248,1688524,2130264,1679966.19207398,8557.80792602059,2119467.35740344,10796.6425965615

In [7]:
manaus_rural_tot_pop_df = manaus_pop_df.drop(columns=['state_abbrev', 'state', 'municipality', 'geocode', 'prop_urb2000', 'prop_urb2010'])

cols = ['urb2000', 'rur2000', 'tot2000', 'prop_rur2000',
    'urb2010', 'rur2010', 'tot2010', 'prop_rur2010',
    'pop_estimated2006', 'pop_estimated2017',
    'urb2006e', 'rur2006e', 'urb2017e', 'rur2017e']

manaus_rural_tot_pop_df[cols] = manaus_rural_tot_pop_df[cols].apply(pd.to_numeric, errors='coerce')

manaus_rural_tot_pop_df

,urb2000,rur2000,tot2000,prop_rur2000,urb2010,rur2010,tot2010,prop_rur2010,pop_estimated2006,pop_estimated2017,urb2006e,rur2006e,urb2017e,rur2017e
0,1396768,9067,1405835,0.00645,1792881,9133,1802014,0.005068,1688524,2130264,1.679966e+06,8557.807926,2.119467e+06,10796.642597

In [8]:
manaus_rural_approx_df = manaus_rural_tot_pop_df.copy()
manaus_rural_approx_df['prop_rur2000'] = manaus_rural_approx_df['prop_rur2000']*100
manaus_rural_approx_df['prop_rur2010'] = manaus_rural_approx_df['prop_rur2010']*100
manaus_rural_approx_df

,urb2000,rur2000,tot2000,prop_rur2000,urb2010,rur2010,tot2010,prop_rur2010,pop_estimated2006,pop_estimated2017,urb2006e,rur2006e,urb2017e,rur2017e
0,1396768,9067,1405835,0.644955,1792881,9133,1802014,0.506822,1688524,2130264,1.679966e+06,8557.807926,2.119467e+06,10796.642597

In [9]:
manaus_rural_approx_df['prop_rur_2006'] = manaus_rural_approx_df['rur2006e']/manaus_rural_approx_df['pop_estimated2006']*100
manaus_rural_approx_df['prop_rur_2017'] = manaus_rural_approx_df['rur2017e']/manaus_rural_approx_df['pop_estimated2017']*100
manaus_rural_approx_df

,urb2000,rur2000,tot2000,prop_rur2000,urb2010,rur2010,tot2010,prop_rur2010,pop_estimated2006,pop_estimated2017,urb2006e,rur2006e,urb2017e,rur2017e,prop_rur_2006,prop_rur_2017
0,1396768,9067,1405835,0.644955,1792881,9133,1802014,0.506822,1688524,2130264,1.679966e+06,8557.807926,2.119467e+06,10796.642597,0.506822,0.506822